"""Results register: what was said on stage against what the pipeline produces.

Reads ``tests/stage_values.yaml`` and ``outputs/tables/golden_actual.yaml``; writes
``docs/RESULTS.md``. With ``freeze=True`` also rewrites ``tests/golden_values.yaml``, the
regression snapshot that the test suite checks the pipeline against.
"""

from __future__ import annotations

import yaml

from .config import ROOT, path

__all__ = ["rows", "write"]

STATUS_NOTE = {
    "reproduced": "pipeline value equals the stage value within the rounding of the slide",
    "differs": "pipeline value is outside the rounding of the slide",
    "superseded": "stage value was computed on an input later found to be wrong",
    "mislabelled": "the number is right and the thing it was attached to is not",
    "qualified": "true for part of the settings; the slide stated it without the condition",
}


def _fmt(v) -> str:
    if isinstance(v, bool) or v is None:
        return str(v)
    if isinstance(v, (int, float)):
        if abs(v) >= 1e4:
            return f"{v:,.0f}"
        if float(v).is_integer():
            return f"{int(v)}"
        return f"{v:.3f}"
    return str(v)


def rows() -> list[dict]:
    stage = yaml.safe_load((ROOT / "tests" / "stage_values.yaml").read_text(encoding="utf-8"))
    actual = yaml.safe_load(path("tables", "golden_actual.yaml").read_text(encoding="utf-8"))
    out = []
    for r in stage:
        val = actual.get(r["key"])
        ok = val is not None and abs(float(val) - float(r["stage"])) <= float(r["tol"]) + 1e-12
        status = r.get("force") or ("reproduced" if ok else "differs")
        out.append(
            {
                **r,
                "value": val,
                "status": status,
                "corrected": actual.get(r["corrected_key"]) if r.get("corrected_key") else None,
            }
        )
    return out


def write(freeze: bool = False) -> None:
    actual = yaml.safe_load(path("tables", "golden_actual.yaml").read_text(encoding="utf-8"))
    rs = rows()
    counts: dict[str, int] = {}
    for r in rs:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    lines = [
        "# Results register",
        "",
        "Generated by `python scripts/run.py register` from `tests/stage_values.yaml` and",
        "`outputs/tables/golden_actual.yaml`. Do not edit by hand.",
        "",
        "## 1. Numbers shown on stage, 3 September 2026",
        "",
        f"{len(rs)} numbers: " + ", ".join(f"{v} {k}" for k, v in sorted(counts.items())) + ".",
        "",
    ]
    lines += [f"- **{k}**: {STATUS_NOTE[k]}" for k in sorted(counts)]
    lines += [
        "",
        "| slide | claim | on stage | pipeline | status | corrected value | note |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rs:
        lines.append(
            f"| {r['slide']} | {r['claim']} | {_fmt(r['stage'])} | {_fmt(r['value'])} | {r['status']} | "
            f"{_fmt(r['corrected']) if r['corrected'] is not None else ''} | {r.get('note', '')} |"
        )
    used = {r["key"] for r in rs} | {r.get("corrected_key") for r in rs}
    lines += ["", "## 2. Numbers produced by the pipeline and not shown on stage", "", "| key | value |", "|---|---|"]
    lines += [f"| `{k}` | {_fmt(v)} |" for k, v in sorted(actual.items()) if k not in used]
    (ROOT / "docs" / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    summary = {"deck_numbers": len(rs), "deck_corrected": len(rs) - counts.get("reproduced", 0)}
    summary.update({f"deck_{k}": counts.get(k, 0) for k in STATUS_NOTE})
    path("tables", "register_counts.yaml", mkdir=True).write_text(yaml.safe_dump(summary), encoding="utf-8")
    if freeze:
        snap = [
            {"id": k, "value": v, "tol": (0 if isinstance(v, (int, bool, str)) else 1e-4)}
            for k, v in sorted(actual.items())
        ]
        header = (
            "# Regression snapshot of every number the pipeline produces.\n"
            "# Written by `python scripts/run.py register --freeze`; tests compare a fresh run with it.\n"
        )
        (ROOT / "tests" / "golden_values.yaml").write_text(
            header + yaml.safe_dump(snap, allow_unicode=True, sort_keys=False), encoding="utf-8"
        )
